bcgov/gis-pantry

- scripts/qgis_perf_test.py
Add a script that can be used to quickly benchmark (2-3 min) machines using QGIS, Python 3
> add qgis performance benchmark script

- recipes/qgis/Oracle-to-QGIS/Oracle_2_Qgis.py
- recipes/qgis/Oracle-to-QGIS/README.md
created new file for bc gov so that oracle datasets can be pulled into QGIS faster / easier using python
> New qgis to oracle

- docs/getting_started_with_ogr/doc/ogr2ogr_start.md
> Fixed text

- docs/getting_started_with_ogr/README.md
> Fixed image links

- recipes/ogr2ogr/ogrFromBCGW_csv/readme.md
Fixed broken image links in readme.md
> Fixed broken image links in readme.md

- docs/getting-started-with-QGIS/doc/plugins.md
Hi,
I have updated the plugin doc.
> plugin md update

- docs/getting-started-with-QGIS/doc/expressions.md
-Added _select by expression query_ section
-Added _select by geometry query_ section (not the same as select by location)
-Added _geometry expressions_ section (just links to QGIS documentation and other sections in this page)
-Fixed some broken links
> Finished expressions.md

- docs/getting-started-with-QGIS/README.md
data link was broken. Changed data.md to working-with-data-in-QGIS.md
> Update Readme Data Link

- recipes/ArcGIS_API_Python/Content_Modification/Content_Modification.md
- recipes/ArcGIS_API_Python/Content_Modification/Update_AGOL_Featureservice_with_FGDB_Feature.ipynb
ArcGIS API Update FS with FGDB feature service
> ArcGIS API Update FS with FGDB feature service

- recipes/s3_objectaccess/README.md
- recipes/s3_objectaccess/create_presigned_url_for_s3_objects.py
Pull request from fork https://github.com/webgismd/GIS-pantry
> new s3 access folder

- scripts/overwrite/README.MD
- scripts/overwrite/overwrite_FS.py
first pull request, sorry if I'm doing something wrong. Also not sure if copying code from a forum (attribution listed in readme and in the script) can be considered plagiarism/copyright violation?
> Added overwrite_FS script

- recipes/ArcGIS_API_Python/Content_Modification/overwrite/README.MD
- recipes/ArcGIS_API_Python/Content_Modification/overwrite/overwrite_FS.py
Credit to Ada Li, FLNR for identifying the need and adding this capability.
 
1. Added a test for type of input (featureclass or a table) - now can overwrite latter too. 
2. Based on the type of input type of conversion to a temp GDB changes, and call for the API changes too.
3. Added password as one of the inputs to instantiating the class to make it easier to call the object/method externally (i.e. can preset password for a run, don't need to wait until the script gets to the line where GIS object is created).
4. Added the ability to accept shapefile input.
5. Updated Readme doc accordingly.
> Added the ability to overwrite hosted tables

- README.md
- docs/Using-GitHub.md
A couple of tiny updates to make sure I am doing this right
> First pull req

- docs/ago/ago-tips-n-tricks/Picture_Symbology.md
- docs/ago/ago-tips-n-tricks/how-to.md
I added documentation to point to updated URL of AGO assistant, as well as added documentation on how to add custom symbology in new Map Viewer and how to add endless grouped layer widgets in WebAppBuilder.
> Improving documentation for AGO tips and tricks

- recipes/ArcGIS_API_Python/Administration/ArcGISOnline_item_backup/JSON_Backup.py
- recipes/ArcGIS_API_Python/Administration/ArcGISOnline_item_backup/readme.md
Added a script that backs up ArcGIS Online applications (map/dashboard/experience builder/etc).
> Added ArcGIS Online backup script

- recipes/ArcGIS_API_Python/Content_Modification/Webmap_Modification/generic_map_dash_changes.py
- recipes/ArcGIS_API_Python/Content_Modification/Webmap_Modification/readme.md
- recipes/ArcGIS_API_Python/Content_Modification/Webmap_Modification/usage_example.py
Made a few fixes to variable and module localization. This makes the class importable. update usage example and readme to reflect changes.
> Made a few minor changes to module localization

- recipes/csv_reader_writer/README.MD
- recipes/csv_reader_writer/csv_class.py
- recipes/csv_reader_writer/csv_class_SAMPLE_CODE.py
Added a snippet for a class that reads/writes a csv to a list of python dictionaries. 
- csv_read_write.py contains the code
- csv_read_write_SAMPLE_CODE.py contains use samples
- README.MD contains additional notes on file format and python version checking functions.
> CSV Reader Writer snippets

- scripts/keyring-example/keyring_example.py
Keyring example added for test purposes only.
> added keyring example

- _getting-started/Gis-Pantry-Docs/GIS_Pantry_QuickStart.md
- _getting-started/Gis-Pantry-Docs/GitHub_Account_Set_Up.md
- _getting-started/Gis-Pantry-Docs/GitHub_Learning_Resources_for_New_Users.md
Did some small formatting edits:
In Account Set up added a line on two-factor authentication, 
Created a new File with some introductory knowledge on terminology and web learning resource links
Changed the file location for GIS Pantry QuickStart and added some hyperlinks
> Formatting Edits 

- _getting-started/Script-Template/readme.md
Updated readme.md in script template folder
> Updated readme.md

- README.md
- _getting-started/Script-Template/.vscode/settings.json
Re-organized the Pantry Help docs extensively to make them more obvious and intuitive to newcomers. 
Modified several files, some extensively
Removed redundant docs, but included their novel content in better locations
Maddi and I reviewed / Discussed at length
Because the folder structure is different, and file names have changed, there are merge conflicts with some of the changes others have made since I forked the repo. 
Any help from more experienced GitHub users is welcome! 
I am new to pull requests, and this one is a bit complicated.
Jeremiah
> Major Re-Org of the GIS Pantry Docs + Multiple edits to files, name changes, folder structure changes, etc. 

- docs/ago/ago-tips-n-tricks/link-shortener.md
- docs/sql/oracle-sql-geometry-in-dbeaver.md
> fixed link typo
